**[To predict the salaries of the following candidates] **

(https://github.com/codebasics/py/blob/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv)

In [14]:
#to convert a word to a number

!pip install word2number

  Created wheel for word2number: filename=word2number-1.1-cp36-none-any.whl size=5587 sha256=01f8f584faf1087a60ddd4e917855d4b2e93c68f6dd764315388501f2a74424e
  Stored in directory: /root/.cache/pip/wheels/46/2f/53/5f5c1d275492f2fce1cdab9a9bb12d49286dead829a4078e0e
Successfully built word2number


In [15]:
import pandas as pd                 ##to open csv file, to create a data frame
import numpy as np                  ##creates array
import matplotlib.pyplot as plt     ##to do data analysis and visualization
import seaborn as sns               ##visualize random distribution
%matplotlib inline                  ##used for plotting
from sklearn import linear_model    ##features various algorithms
from word2number import w2n

In [10]:
d= pd.read_csv("hiring.txt")        ##to read the file
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [11]:
d.experience= d.experience.fillna("zero")   ##substitues the empty places with zero
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [16]:
d.experience=d.experience.apply(w2n.word_to_num)   ##convert word to number
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [30]:
import math
median_test_score = math.floor(d['test_score(out of 10)'].mean())     ##gives integer type values
median_test_score

7

In [31]:
d['test_score(out of 10)']=d['test_score(out of 10)'].fillna(median_test_score)     ##substitue the null values with the integer values
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [32]:
reg=linear_model.LinearRegression()
reg.fit(d[['experience','test_score(out of 10)','interview_score(out of 10)']],d['salary($)'])  ##train the data

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [33]:
reg.coef_                ##gives coefficient of the values

array([2812.95487627, 1845.70596798, 2205.24017467])

In [37]:
reg.predict([[2,9,6]])    ##output of the algorithm after being trained

array([53205.96797671])

In [39]:
reg.predict([[12,10,10]])

array([92002.18340611])